name: pawn_uis
description: "Pawn's Some UI components"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  auto_route: ^8.0.3
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  scrollview_observer: ^1.19.1
  darq: ^2.0.0
  extended_nested_scroll_view: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true


