// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

/// {@template assets_generator.assets_images_asset_gif.preview}
/// ![](e:\code\pawn_uis\assets/images/asset.gif)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}