// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_images_asset_gif.preview}
  static const String assets_images_asset_gif = 'assets/images/asset.gif';
}
